on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: drake-make-plan

jobs:
  drake-make-plan:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "pkgload"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Rebuild analysis
        run: |
          pkgload::load_all()
          drake::make(plan)
        shell: Rscript {0}
